eureka:
   client:
     service-url:
       defaultZone: http://localhost:8765/eureka
spring:
   cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
